### ISSUE TITLE
Setting node size

### ISSUE THREAD

**Issue by GiulioRossetti** [Zsailer/nx_altair#12]
Hi,
I'm trying, without success, to assign a specific size to each node. 

If I get it right this should be possible by linking the node_size property to a node attribute.
Unfortunately, the result is a graph with all nodes represented as dots (size=1 i guess).

What am I doing wrong?

Here's my code:

```
for n in g.nodes():
    g.nodes[n]['name'] = n
    w = randint(300, 1000)
    g.nodes[n]['size'] = w
    print(w)
    
pos = nx.spring_layout(g)

viz = nxa.draw_networkx(
    g, 
    pos=pos,
    node_color='#ff0000',
    width='weight',
    edge_color='black',
    node_label='name',
    node_size='size'
)

viz.interactive()
```

**Comment by Zsailer** [comment]
@GiulioRossetti, you're right! This should work. I'll let you know when I have this fixed.

**Comment by GiulioRossetti** [comment]
@Zsailer thanks again for your work! I'll wait for updates then.

**Comment by Zsailer** [comment]
Sorry for not returning to this issue sooner, @GiulioRossetti. This seems to be working for me. If you're still having issues, feel free to reopen this issue. Thanks!
