### ISSUE TITLE
Ugly default node borders

### ISSUE THREAD

**Issue by nrchtct** [Zsailer/nx_altair#15]
Hi @Zsailer,

Thanks a lot for your work on this library.

It seems an Altair or Vega Light update has added default borders that might have not been included in prior versions. When I run the examples on Colab (on right side below) with current Altair 4.1, the network nodes receive distracting blue node outlines, which are not included in the ipynb files generated two years ago.

![ugly default borders](https://user-images.githubusercontent.com/578924/83567613-20717900-a522-11ea-8a1e-cfcb3c1d9bf9.png)

Is there any chance to make these node borders transparent or width=0?

All the best & thank you!
Marian

**Comment by Zsailer** [comment]
Thanks for reporting, @nrchtct. I added a fix in #16 and published a new version on PyPI. This should work in `nx-altair` v0.1.6. You can upgrade using `pip install nx_altair --upgrade`. 

You can adjust the edges around the nodes using the `linewidths` argument:

```python
nxa.draw_networkx(
    ...,
    linewidths=1.0,
    ...
)
```
Closing for now, but if you're still having issues please reopen!

**Comment by nrchtct** [comment]
This is great! Thank you for the quick response, @Zsailer
